tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "dockutil"
brew "exa"
brew "fzf"
brew "git"
brew "gnupg"
brew "hub"
brew "mas"
brew "neofetch"
brew "nmap"
brew "pinentry-mac"
brew "shellcheck"
brew "ssh-copy-id"
brew "tealdeer"
brew "telnet"
brew "thefuck"
brew "tmux"
brew "topgrade"
brew "zplug"
cask "1password-cli"
cask "adoptopenjdk8"
cask "appcleaner"
cask "balenaetcher"
cask "cyberduck"
cask "discord"
cask "font-fira-code"
cask "google-chrome"
cask "google-drive-file-stream"
cask "microsoft-office"
cask "microsoft-teams"
cask "multimc"
cask "onyx"
cask "parsec"
cask "postman"
cask "rectangle"
cask "suspicious-package"
cask "tableplus"
cask "the-unarchiver"
cask "tinkerwell"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Apple Remote Desktop", id: 409907375
mas "Balance Lock", id: 1019371109
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
mas "Wipr", id: 1320666476
