# List of remote machines with Topgrade installed on them
remote_topgrades = ["twinkies", "christcs", "cpc"]

# Cleanup temporary or old files
cleanup = true

[git]
# Additional git repositories to pull
repos = [
    "~/src/*/"
]
