# List of remote machines with Topgrade installed on them
remote_topgrades = ["bakery", "christcs", "cpc", "thefryer"]

# Cleanup temporary or old files
cleanup = true

[git]
# Additional git repositories to pull
repos = [
    "~/src/*/"
]
