#!/bin/sh

if ! command -v dockutil >/dev/null
then
  echo "Install dockutil first!" >&2
  exit 1
fi

dockutil --remove all --no-restart

dockutil --add /System/Applications/Launchpad.app --no-restart
dockutil --add /Applications/Google\ Chrome.app --no-restart
dockutil --add /System/Applications/Messages.app --no-restart
dockutil --add /System/Applications/Music.app --no-restart
dockutil --add /System/Applications/App\ Store.app --no-restart
dockutil --add /System/Applications/Utilities/Terminal.app --no-restart
dockutil --add /System/Applications/System\ Preferences.app --no-restart
dockutil --add /Applications/Visual\ Studio\ Code.app --no-restart
dockutil --add /Applications/DBeaver.app --no-restart
dockutil --add /Applications/Steam.app --no-restart
dockutil --add "$HOME/Downloads" --display stack --no-restart

/usr/bin/killall Dock >/dev/null 2>&1
