#!/bin/bash
set -e

if ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_housecocc" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin housecocc.1password.com cayce@caycehouse.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get egcwqljukjf2zl7exyxk3rhlqi .ssh/id_ed25519
onepassword_get l5kueseqyffsja3fyejrmnhjt4 .ssh/id_rsa

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    echo "Install jq first!" >&2
    exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item roqn5chdwkgs2vp5zjer2gqmia | jq -r '.details.sections[0].fields[1].v')
  cat > "$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K
