#!/bin/bash
set -e

if ! [ -L ~/.ssh ]; then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null; then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_housecocc" ]; then
    echo "Logging into 1Password..."
    eval "$(op signin housecocc.1password.com cayce@caycehouse.com)"
  fi
}

if ! [ -f "$HOME/.secrets" ]; then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null; then
    echo "Install jq first!" >&2
    exit 1
  fi
  onepassword_login
  GITHUB_TOKEN=$(op get item roqn5chdwkgs2vp5zjer2gqmia | jq -r '.details.sections[0].fields[1].v')
  cat >"$HOME/.secrets" <<EOF
export GITHUB_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi
