#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd "$(dirname "$0")/.." || exit

script/dock
script/extract-onepassword-secrets
script/terminal

composer global require laravel/valet
"$HOME"/.composer/vendor/bin/valet install
