#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd "$(dirname "$0")/.." || exit

script/dock
script/extract-onepassword-secrets
script/install-vscode-extensions
script/terminal

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

if [ "$SHELL" != '/bin/zsh' ]
then
  sudo chsh -s '/bin/zsh' caycehouse
fi