name: Test Install Scripts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'install.sh'
      - 'install.ps1'
  pull_request:
    branches:
      - main
    paths:
      - 'install.sh'
      - 'install.ps1'

jobs:
  install:
    name: Test install scripts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      CHEZMOI_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODESPACES: true
    steps:
      - uses: actions/checkout@v4
      - name: Run install script
        run: ./install.sh
        shell: bash
        if: matrix.os != 'Windows'
      - name: Run install script
        run: ./install.ps1
        shell: pwsh
        if: matrix.os == 'Windows'
