name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Validate syntax
        run: bash -n *.sh

      - name: Test script/setup
        run: bash script/setup

      - name: Install Oh My Zsh
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

      - name: Test zshrc
        run: zsh -c "source ~/.zshrc"
