name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Validate syntax
        run: bash -n *.sh

      - name: Test script/setup
        run: bash script/setup
      
      - name: Install zplug from Homebrew
        run: brew install zplug

      - name: Test zshrc
        run: zsh -c "source ~/.zshrc"
